name: PropertyGuilds
main: amao.krzysek.propertyguilds.PropertyGuilds
description: Guilds system for your server
version: 0.1
author: krzysek (deew)
commands:
  guilds:
    description: Main command of PropertyGuilds
    permission: propertyguilds.default
    permission-message: You don't have permission to this